### ISSUE TITLE
謝謝你的心得

### ISSUE THREAD

**Issue by azole** [gsn94561266/git-workshop#3]
「現在就覺得不要想那麼多，往自己有興趣的方向發展，有熱情比較重要。」 --> 能這樣想，我覺得很棒

我經常覺得用「沒天份」來侷限自己的人，其實都只是在找偷懶跟失敗的藉口而已，我曾有學生在長達 4 個月的轉職過程中沒有放過任何一天假，每一天，包括端午連假的每一天，每天早上九點就出現在教室，一直拼命學習到晚上11 點多，回家沖個澡睡覺，隔天起來繼續，最後非常成功地轉職了，如果有人可以這樣拼命， 而且，這不是一個人，他們是全班有 2/3 的人都這麼拼，那我們在還沒有這麼努力前，好像沒有資格說自己「沒天份」對吧？

「你必須非常努力，才能毫不費力」，如果還無法到毫不費力的程度，那就可能還需要更努力，或是還需要更多時間去累積這個努力，所以，千萬不要輕易地說出「沒天份」這三個字。相對地，如果有人學得很好、表現得很好，我們用「有分份」、甚至是「天才」去形容對方，那我認為，這對對方來說，也根本是一種侮辱，污辱他所付出的努力與時間。

這世界真的有天才存在，但很少，我們身邊大部分能把事情做得不錯的人，大概都脫離不了兩件事：他很努力，但他不是傻傻地拼，他有刻意地、有意識地為自己找到合適的學習方式。

做為大人，努力跟找到適合自已的方法，都是自己的責任，不是教育制度的，也不是老師的，是你自己的，希望你能為自己找到適合的努力方向，加油，不要放棄！

**Comment by gsn94561266** [comment]
謝謝老師～
